### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by akshayvijayan** [Mahmoud-Elbattah/Predicting_ASD#1]
Please provide the dataset files.

**Comment by Mahmoud-Elbattah** [comment]
Hi Akshay,
Thanks for your interest in our work.
The dataset along with metadata is shared on Figshare below.
https://figshare.com/s/5d4f93395cc49d01e2bd

The original paper of the dataset is currently in press.
Carette, R., Elbattah, M., Dequen, G., Guérin J.L., & Cilia F. (2018). Visualization of Eye-Tracking Patterns in Autism Spectrum Disorder: Method and Dataset. _In Proceedings of the Thirteenth International Conference on Digital Information Management (ICDIM 2018_). IEEE.

Please don’t hesitate to contact me should you have any questions.

Regards,
Mahmoud

**Comment by akshayvijayan** [comment]
> Hi Akshay,
> Thanks for your interest in our work.
> The dataset along with metadata is shared on Figshare below.
> https://figshare.com/s/5d4f93395cc49d01e2bd
> 
> The original paper of the dataset is currently in press.
> Carette, R., Elbattah, M., Dequen, G., Guérin J.L., & Cilia F. (2018). Visualization of Eye-Tracking Patterns in Autism Spectrum Disorder: Method and Dataset. _In Proceedings of the Thirteenth International Conference on Digital Information Management (ICDIM 2018_). IEEE.
> 
> Please don’t hesitate to contact me should you have any questions.
> 
> Regards,
> Mahmoud

Thank you.

**Comment by akshayvijayan** [comment]
But the dataset mentioned in the files are different from that I downloaded from the link that you shared. Can you please help me to figure out the solution. Also please help me to find the order of execution of files. Thanks in advance.

**Comment by Mahmoud-Elbattah** [comment]
Hi Akshay,
Please kindly outreach me at <mahmoud.elbattah@u-picardie.fr>
I need to CC other authors, and please try to give a bit more details.
Reagrds,
Mahmoud
