### ISSUE TITLE
Can you share the dataset or the data source about where and how  you get those?

### ISSUE THREAD

**Issue by harvardfinalproject** [Mahmoud-Elbattah/Predicting_ASD#2]
Can you share the dataset or the data source about where and how  you get those? I need to do a class project for this, many thanks!

**Comment by Mahmoud-Elbattah** [comment]
Hello there
Here is the dataset:
https://figshare.com/articles/dataset/Visualization_of_Eye-Tracking_Scanpaths_in_Autism_Spectrum_Disorder_Image_Dataset/7073087

Publications:
https://ieeexplore.ieee.org/abstract/document/8846967
https://ieeexplore.ieee.org/abstract/document/8856904
https://www.scitepress.org/Papers/2019/74026/74026.pdf

Regards,
